version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_cursomc2
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=testdb
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    ports:
    - "3306:3306"
    volumes:
    - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:
