version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_cursomc2
    environment:
      - MYSQL_DATABASE=cursomc2_spring
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

    ports:
    - "3306:3306"
    volumes:
    - cursomc2_data:/var/lib/mysql

volumes:
  cursomc2_data:
