spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#Para mostrar no console no mesmo level do debug, mesma linha
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG

#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true